group: travis_latest
language: node_js
node_js: node
cache: yarn

addons:
  firefox: latest
  chrome: beta

before_install:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1280x800x24 &>/dev/null &

deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email:
    secure: pbthIRLTxlov4QICPFJic9qAG9bz8Gb7d8Yhq37QRT9lJlIgj+BjltsxKaksdVebFU+LJZ4W1UIOR9B8LpQLoVDU74Ff4dOf9qvmUyK/Y2vMsGfvSZbAv4/eutO9HLmRNrr7pgM6RPw/dSVipdf0Jw64+W9rdxgxId2hPipGvHm9r/vv7kr7SsY5APjuz6OKdfhCQ1DWdhZ4h3B6GllRw5JL2IEGiOtty5ggaggJbtWlIGAqmdbZqFcv2lafTVqvFObr0+H3++jG/28GD4Y3SByS7cIT90UXZ0EQ4GUlJs3X0tXLYxD8p9yLKgu5mo1dTNgJ2uWp5KyU8hOU+/9jRL88OWQIZPfUiWC13dNbRTPTQQsaQ9s2cesYDm7tPlDUShFHB9tPyUfVzLr702xiuGDOS/a3Tvjb+o9KMUCTQYuRvgZOijjQoFBxrbi7F1/9EMGMKfYGP7vRX7HsU6ZQ/oxVvIuRlOH0+g6QOIMsBhgz1BVyttq8FJ+JPDM0JdwOQpD2sZo6x0DTwqSAeq3h6vjTVavS+CfoyJPkom//+eKJM0ilt/a73UvszfGJ349MjEAm/Ejv8ILVOTiIphViVMYU3FHiX/AQP1dHMxi/tjGeFyiUVkT6CKi1a/AftgW5a98eF2jX+WlKYSb7T1Q1AsW4glQE83lnURHODq8Ikvc=
  api_key:
    secure: DcmnMlvsVBNR7W0Li8snGdyFJvcy+fdhh3CWIE52gBb5s7Du7bZMDWe6g8Buvz652uAW7UB0JEe7lcNm90H11uYjPxKB2cUL7IZEQ7T9zW5gO9mg8oc20lPeQzQsCYxSLIt32X6SNM7lPwtzu0Sa665x9omqi4dAkPQvnFYKELH3xi97JQkJglWlSEM7AUJ/iJxWieY/RYYtzpRBi8eiIf1WlarN5/QmSrdBVdX8196JcBFSny80HjX0RQ4YIU3adjPYZhboMNBL+5dupamJjI6LKCNZZH5P5g0lGv75XA3CJkBmaxQIG9pFPenPznQT1FsmmHHoHGZccpgkTxvzOqdUdfCMPo2/jYUkfoLG4Qm7qdnoZ2h85t6DB5m/2b22Ky/GP/r9mmP4/FNk9XgNHUSwCHMVWB+/0fcda5m/IXvHG8to045l/BmOtgC2O708BiZXxfSLwTbtx48PzGsH/n70plx3VPoiqQJONEj+XOq5N+sravpKztL8uuBmeYgzBklMaV08W6QXb9do1MBAcZ3la8qiMDU20j6DiQObw7a48dWiLaESfazKGMKJysggxd0XYn1zxzmUDXCHjsc1P4GsS7ZZIQZHorSHa+yb7s4ZdrXy7Vokasni6/XsbAWjEkPlkcjbo0cNNV/+NoSCIJHvzURfNiOzYDEGuRTO/xI=
